baseURL = "https://mohamed-hanfy.github.io/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = false

[languages]
  [languages.en]
    title = "Mohamed Hanafy"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    
    [languages.en.params.logo]
      logoText = "Mohamed Hanafy"
      logoHomeLink = "/"
    
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/"
    [[languages.en.menu.main]]
      identifier = "blog"
      name = "Blog"
      url = "/posts"
      weight = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
